services:
  - docker
  - riak

script:
  - docker run -p 9092:9092 -p 2181:2181 --env ADVERTISED_HOST=$(hostname) --env ADVERTISED_PORT=9292 -d spotify/kafka
  - docker load -i riak.tar
  - docker run -p 8098:8098 -d riak:latest
  - sleep 10
  - sudo riak-admin bucket-type create xfiles
  - docker ps
